- add SQ 7.7 for testing - remove CoreMetrics.FILES metric, plugin no more allowed to set it - remove Directories metric, no more supported by SQ - file extensions must be unique assigned to a plugin: resolve .h conflict with c and cxx plugin - remove folders with XML files from analysis: plugin handling XML files is part of SQ 7.7 now
ERROR: Language of file 'PathHandling/PathHandle.h' can not be decided as the file matches patterns of both sonar.lang.patterns.c++ : **/*.cxx,**/*.cpp,**/*.cc,**/*.c,**/*.hxx,**/*.hpp,**/*.hh,**/*.h and sonar.lang.patterns.c : **/*.c,**/*.h
make file extension unique: ERROR: Language of file 'tests/unittests/stdafx.h' can not be decided as the file matches patterns of both sonar.lang.patterns.c++ : **/*.cxx,**/*.cpp,**/*.cc,**/*.c,**/*.hxx,**/*.hpp,**/*.hh,**/*.h and sonar.lang.patterns.c : **/*.c,**/*.h